### ISSUE TITLE
Convert docx file to JATS XML as a prototype

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#1]
## Problem / Motivation

- WHO Editorial create a final `.docx` file
- WHEN and WHERE It will happen as part of an S3 bucket zip file delivery workflow to automatically convert `.docx` content to JATS XML
- WHAT Convert the `.docx` file contents to JATS XML to be used in typesetting software
- WHY Can keep the current procedure where the decision letter and author response the content is put into a `.docx` file

## Proposed solution

- To investigate a solution using `pandoc` to convert the `.docx` file to JATS or some intermediate format
- Additional code written in Python to clean up and format the JATS into the final desired output
- Populating python objects with data as an intermediate representation of the content may also be an option to explore, similar to other eLife Python conversion libraries

## Clarification needed and assumptions

- Want to support inline style extraction (bold, italic, sub, sup), hyperlinks, mathml/tex math extraction
- Additional more finely-grained issues will be created for each property of the decision letter

---

## Tasks

- [x] Create initial code repository with Python and automated test framework
- [x] Collect and add some sample `.docx` data
- [x] Get some output of `.docx` using `pandoc` to demonstrate viability
- [x] Create or confirm additional issues for specific tasks exist to be done next

## Technical notes
- Technology: pandoc, Python

## User interface / Wireframes

@Melissa37  here is a starting place for the code of the project

**Comment by Melissa37** [comment]
👍

**Comment by gnott** [comment]
Fixed in https://github.com/elifesciences/decision-letter-parser/pull/11
