### ISSUE TITLE
Figure parsing

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#2]
## Problem / Motivation

- WHO Editorial to include figures in the decision letter / author response
- WHEN and WHERE do they want it? When `.docx` files are converted
- WHAT Parse figure content from the `.docx` file but it can remain simple in the output
- WHY Figures are sometimes included

## Proposed solution

- Probably use the standard `.docx` conversion software to extract the text and include it in the output
- May look at `.zip` file contents for a figure file and add a reference to it somewhere in the JATS output

## Clarification needed and assumptions

- Q. Where a decision letter refers to "Figure 1", should the automated
conversion process detect these and insert special XML, or is the typesetter
expected to mark these?
A. No, they should remain as plain text. The reason being that figures can move around in the review process and so would be confusing if it links to figure 1 but that is now figure 2. Better to leave as plain text in these assets.

---

## Tasks

- [x] Parse the figure content from the `.docx` file
- [x] Format the figure content into the final JATS XML output
- [x] Discussion and documentation about figure file naming formats
- [x] Docx files currently contain wrappers like `<Author response image 1>`
- [x] Will probably need to also support recognising a wrapper for `<Decision letter image 1>`
- [x] In examples, the caption has a wrapper like `<Author response image 1 title/legend>`

## Technical notes
- We could use this technology
- More notes or suggestions

**Comment by Melissa37** [comment]
👍 

Should we include the file naming convention for author response images in this ticket? Or link to another ticket where they are dealt with?

**Comment by gnott** [comment]
This is a pretty thin and simple issue so far, there is room for discussion about figures in all respects, including file naming formats.
