### ISSUE TITLE
Zip file format for decision letter package

### ISSUE THREAD

**Issue by gnott** [elifesciences/decision-letter-parser#4]
## Problem / Motivation

- WHO Editorial to put `.docx` and any figure or supplemental files as part of a decision letter / author response in a single file, a `.zip` file, to be copied into an S3 bucket
- WHEN and WHERE To be produced prior to adding a decision letter to an S3 bucket and before any automated workflow is run
- WHAT A single `.zip` file, possibly with a specific file naming format
- WHY Ensures only one S3 bucket notification is triggered when a decision letter is supplied

## Proposed solution

- Documentation about the specific zip file name formats allowed, and file name formats for any image / video / supplementary files inside
- May want a manifest file inside the `.zip` that specifies details about the contents

## Clarification needed and assumptions

- Do we ever need a silent delivery of a corrected decision letter? The file name may differ for a silent correction

---

## Tasks

- [x] Discuss file name options
- [x] Create a sample `.zip` file
- [x] Documentation for the file name format

## Technical notes
- Zip files

## User interface / Wireframes

@Melissa37 any suggestions on file naming?

**Comment by Melissa37** [comment]
👍 

@acollings we should discuss this with our teams - preferred file naming and also whether we've ever needed to send a second version through.

**Comment by gnott** [comment]
Is it possible to review the zip file naming for decision letter content? I think to continue building the logic I would like to create one or two sample zip files. @Melissa37

**Comment by Melissa37** [comment]
This is what the editorial/production team decided:

- Zip file format for decision letter package
- MH looking for something sensible
- Last five digits: 12345.zip, upload to Amazon bucket
- Hopefully won’t need to deposit to G drive

Basically, what you think would be best should work. You happy to propose something and I'll take it back?

**Comment by gnott** [comment]
That is a good start, thanks!

I was also curious about the naming of the files inside the zip file, for example, of the figure files (if present), and how they would relate to the placeholders inside the `.docx` content in order to match up the right figure to the right caption.

**Comment by gnott** [comment]
I think perhaps for some additional clarity, the zip file name could be `elife-12345.zip` (instead of just numbers) - what do you think @Melissa37?

The naming of the insides of the zip file are top of mind with me right now too, because I'm planning on incorporating a sample into the code project in the next week or so. We can change the naming slightly if required in the future, but it would be helpful to get some feedback.

**Comment by Melissa37** [comment]
Looks good to me!
@acollings this would work right?

**Comment by acollings** [comment]
Yes, sounds good, thank you @gnott!

**Comment by gnott** [comment]
I'm taking a close look at this issue again, it being the next in the critical path to project completion.

The `.zip` file naming we discussed a little and sounds good, e.g. `elife-00666.zip`.

For the  naming of the `.docx` file inside the zip so far I've gone with e.g. `elife-00666.docx`, since it is simple and follows the zip file naming style. I hope this is acceptable, and can be revisited later if you also want to have an author name in the file name.

The figure file naming we did not discuss here. For simplicity, in the first `.zip` file sample I will create I will use file names exactly like the file names that will be assigned to figures. For the article `391122` sample, those will be:

- `elife-39122-sa2-fig1.jpg`
- `elife-39122-sa2-fig2.jpg`

When creating decision letter + author response zip files at first I hope it is acceptable to ask you to name figure images with this style of naming.

The `sa2` portion refers to the author response, and `sa1` would be used for an image in the decision letter.

The file extension `.jpg` is acceptable, and I understand `.tif` and possibly `.png` will be allowed too. It is probably best to make sure these file extensions include only lower-case letters and no upper-case.

Video file names will be similar, like this

- `elife-00666-sa2-video1.mp4`

I think multiple types of videos are also allowed, being all the ones Glencoe currently supports as inputs for transcoding to other formats.
